spring:
  datasource:
    url: 
    driver-class-name: oracle.jdbc.OracleDriver
    username: 
    password: 
  hikari:
    minimum-idle: 10
    maximum-pool-size: 30
    idle-timeout: 30000 # in milliseconds (30 seconds)
    connectionTimeout: 30000
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect